# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 08:11
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=account.models.Profile.upload_user_image),
        ),
    ]
