# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to=b'testing/'),
        ),
    ]
