# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160725_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to=b'images/%y/%m/%d'),
        ),
    ]
